using System;
using GolBox.Application.Interfaces;

namespace GolBox.Application.Security;

public sealed class QrIdentity
{
    public bool IsValid { get; init; }
    public Guid? UserId { get; init; }
    public long? TimeStep { get; init; }
    public string Kind { get; init; } = "unknown";
    public string? ErrorMessage { get; init; }
    public string Fingerprint { get; init; } = string.Empty;

    public static QrIdentity Fail(string message) =>
        new() { IsValid = false, ErrorMessage = message, Kind = "invalid" };

    public static QrIdentity Hmac(Guid userId, long timeStep) =>
        new()
        {
            IsValid = true,
            UserId = userId,
            TimeStep = timeStep,
            Kind = "hmac",
            Fingerprint = $"hmac:{userId:D}:{timeStep}"
        };

    public static QrIdentity LegacyGuid(Guid userId) =>
        new()
        {
            IsValid = true,
            UserId = userId,
            Kind = "legacy-guid",
            Fingerprint = $"legacy:{userId:D}"
        };
}

/// <summary>
/// Resolves cashier-scanned tokens. Primary path is HMAC (GBQR:user:step:signature).
/// Legacy raw GUIDs are isolated here for transition only and must not be generated by the citizen app.
/// Access JWTs are not cashier QR tokens.
/// </summary>
public static class QrTokenParser
{
    public static QrIdentity Resolve(string? qrToken, IDynamicQrService hmacService)
    {
        if (string.IsNullOrWhiteSpace(qrToken))
            return QrIdentity.Fail("QR kod boş.");

        var token = qrToken.Trim();
        if (token.StartsWith("GBQR:", StringComparison.OrdinalIgnoreCase))
        {
            var validation = hmacService.ValidateDynamicQrToken(token);
            if (!validation.IsValid || validation.UserId is null || validation.TimeStep is null)
                return QrIdentity.Fail(validation.ErrorMessage ?? "Geçersiz QR kod.");

            return QrIdentity.Hmac(validation.UserId.Value, validation.TimeStep.Value);
        }

        return TryLegacyUserGuid(token);
    }

    /// <summary>
    /// Transition helper: a raw GUID is treated as UserId. Do not use for new QR generation.
    /// </summary>
    public static QrIdentity TryLegacyUserGuid(string token)
    {
        if (Guid.TryParse(token.Trim(), out var userId) && userId != Guid.Empty)
            return QrIdentity.LegacyGuid(userId);

        return QrIdentity.Fail("Geçersiz QR kod formatı.");
    }
}
